{
  "language": "java",
  "dist": "xenial",
  "jdk": [
      "15"
  ],
  "cache": {
    "directories": [
        "$HOME/.m2/repository",
        "$HOME/.gradle"
    ]
  },
  "script": [
      "./gradlew clean build"
  ],
  "notifications": {
    "email": [
      {
        "recipients": [
            "mollykelly@hanyang.ac.kr"
        ]
      }
    ]
  }
}