arch: amd64

language: java

jdk:
  - oraclejdk15

cache:
  directories:
    - $HOME/.m2

script:
  - java --version
  - ./mvnw clean install
  - ./mvnw test
# CI 실행 완료 시 작성한 이메일로 알람
notifications:
  email:
    recipients:
      - mollykelly@hanyang.ac.kr